Deprecate Global Ember via new options to the modules plugin
babel/ember-cli-babel pull request #382
Opened 2021-02-22 21:22 UTC by NullVoxPopuli

2021-02-22 21:38 UTC, NullVoxPopuli commented
I don't know how to test this, since we are `require`ing packages in the ember-plugins file

2021-02-26 15:14 UTC, rwjblue requested changes
We can test with `fixturify-project`

2021-02-26 15:14 UTC, rwjblue commented on lib/ember-plugins.js
> +  return pkg && semver.gte(pkg.version, "3.26.0-beta.1");
```suggestion
  return pkg && semver.gte(pkg.version, "3.27.0-alpha.1");
```

2021-03-05 23:19 UTC, patocallaghan commented
👋 @rwjblue I spoke to @NullVoxPopuli and I offered to get this PR over the line for him. I just have a question.

I see we've already updated `ember-plugins.js` to use `useEmberModule` but do we also need to add `useEmberModule` to `babel-options-util.js` too? What's the difference between the two files/usages?

https://github.com/babel/ember-cli-babel/blob/20924faa529cf4f9c6f7cb8fa2c89d968184b620/lib/babel-options-util.js#L132

2021-03-06 01:34 UTC, patocallaghan commented
@rwjblue @NullVoxPopuli I've added a test to `node-tests/addon-test.js` which was set up already to use `fixturify-project`. It seems though these tests don't exercise the logic in `lib/ember-plugins.js` so I had to add the `useEmberModule` logic to `lib/babel-options-util.js` too.

2021-03-06 23:22 UTC, patocallaghan commented
hmm, in the `floating dependencies` CI tests, i.e. `yarn install --no-lockfile`, the ember module gets transpiled to `_ember2` rather than `_ember`. I'm able to reproduce this locally. 

![image](https://user-images.githubusercontent.com/685034/110224284-03fbd600-7ed2-11eb-9021-9d69905c6973.png)

Any idea how the name of the AMD module is determined? why would it appear as `_ember2` in this scenario?

2021-03-07 01:29 UTC, rwjblue commented
@patocallaghan - I think we should bump the babel-plugin-* that we have as dependencies, those failures are due to an update in one of those and bumping + fixing the fixtures in another PR should unblock.

2021-03-07 20:39 UTC, patocallaghan commented
I've put together a PR in https://github.com/babel/ember-cli-babel/pull/385 which upgrades some deps. It mimics what we see with the "floating deps" in CI so it will resolve our issue

2021-03-07 21:00 UTC, rwjblue commented
Hmm, I expected that to fail. Perhaps the issue isn't with one of those plugins?

2021-03-07 21:58 UTC, patocallaghan commented
Ah no it is. Once I rebase this PR against that branch it starts failing. I've updated locally with _ember2 and it works fine

2021-03-07 22:04 UTC, patocallaghan commented
I should say nothing else fails though

2021-03-10 16:12 UTC, patocallaghan commented
@rwjblue I've rebased this against master to pick up the package upgrades. CI looks happy now 🎉

2021-03-10 21:10 UTC, pzuraq approved these changes

2021-03-15 21:30 UTC, patocallaghan commented
@rwjblue any chance this could be merged and released please? I need this and the package upgrade PR in some other repo PRs

2021-03-17 20:38 UTC, rwjblue commented
Closing in favor of #387

2021-03-17 20:38 UTC, closed without merging